### ISSUE TITLE
Forward Proposal events from Voting contract to #voting channel

### ISSUE THREAD

**Issue by branimirangelov** [comrade-coop/apocryph-dao-bot#12]
The goal of the ticket is to publish `Proposal` events from `Voting` smart contract of Apocryph DAO to a dedicated `#voting` channel.

To generate voting proposal you can use Apocryph DAO deployed on rinkeby network and interact with it using `operate.js`.  

**Implementation Notes**
1. As a reference implementation you can use `Apocryph.Dao.Bot.Streams.TransferEvents`
2. To see the interface of Proposal event, take a look at: https://github.com/comrade-coop/apocryph-dao/blob/master/contracts/voting/IVotingBase.sol

**Acceptance Criteria**
1. Display a new entry in `#voting` channel in Apocryph Discord when a new proposal is added

**Comment by aph5nt** [comment]
@branimirangelov how this new entry on discord should look like? event only is passing an id of vote

**Comment by branimirangelov** [comment]
In this iteration, I was thinking to simply show the `vote_id`.

Then we can have dialogs based on the `vote_id` to get more info like rationale, links for voting and etc.

In subsequent increments we might change this by having a more informative messages with embedded rationale and links.

**Comment by aph5nt** [comment]
completed
