### ISSUE TITLE
Implement Vote action widget for Voting smart contract

### ISSUE THREAD

**Issue by branimirangelov** [comrade-coop/apocryph-dao-bot#15]
The goal of the ticket is to implement a small Voting UI widget for voting. The widget will be opened using URL returned by the Discord Bot. 

**Implementation Notes**
1. Introduce a dedicated component for creating a Ethereum transaction for the voting action similar to: https://github.com/comrade-coop/apocryph-dao-bot/blob/master/src/Apocryph.Dao.Bot/ClientApp/src/components/SignAddress.vue
2. For reference you can use the `operate.js` utility of the dao and its `23) function vote(uint256 voteId, uint8 value) returns ()` operation.

**Acceptance Criteria**
1. Correctly configured URL with parameters (e.g. voteId) should open the Voting UI
2. Sending a transaction from the Voting UI (with Metamask) should lead to invocation of the `vote` function of the contract

**Comment by aph5nt** [comment]
done
