### ISSUE TITLE
Implement "view voting rationale" dialog

### ISSUE THREAD

**Issue by branimirangelov** [comrade-coop/apocryph-dao-bot#16]
User should be able to request from the bot to see the voting rationale for a specific `vote_id`. This should be done in a direct message with the bot using `/vote <vote_id>`

**Implementation Notes**
1. This should be implemented as a "dialog", use `GetBalanceDialogStream` as a reference
2. To create an active voting you can use `operate.js` on rinkeby network

**Acceptance Criteria**
1. For an active voting the command should return its rationale when executed on Apocryph Discord

**Comment by aph5nt** [comment]
not relevant anymore
