### ISSUE TITLE
Perper fabric container stops after some time

### ISSUE THREAD

**Issue by aph5nt** [comrade-coop/apocryph-dao-bot#7]
When running perper-fabric from docker-compose, the container stops after some time.
In the container logs we can find the following message:

    5321884 [client-connector-#73] [ERROR] ROOT - JVM will be halted immediately due to the failure: [failureCtx=FailureContext [type=CRITICAL_ERROR, err=class 
    o.a.i.i.mem.IgniteOutOfMemoryException: Out of memory in data region [name=default, initSize=256.0 MiB, maxSize=397.2 MiB, persistenceEnabled=false] Try the following:
      ^-- Increase maximum off-heap memory size (DataRegionConfiguration.maxSize) 
      ^-- Enable Ignite persistence (DataRegionConfiguration.persistenceEnabled)  
      ^-- Enable eviction or expiration policies]]

**Comment by bojidar-bg** [comment]
For Perper 0.7, try passing `--max-data-region-size <some number more than 397>` in `services["obecto.perper.fabric"].command` in `docker-compose.yml`.

**Comment by aph5nt** [comment]
ok, fixed;
change will be a part of different commit
